repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.292
  hooks:
  - id: ruff
    args:
    - --fix
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
